import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";
import Footer from "@/shared/Footer";
import Layout from "@/components/Layout";
import { Toaster } from "react-hot-toast";
// import Header from "@/components/header/Header"
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Onlines-Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
       <Layout>
       <Header />
        {children}
        <Footer/>
        <Toaster position="bottom-right" toastOptions={{
          duration:3000,
          style:{background:'#000000', color:'#FFFFFF'}
        }}/>
       </Layout>
      </body>
    </html>
  );
}
