import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";
import Footer from "@/shared/Footer";
import Layout from "@/components/Layout";
// import Header from "@/components/header/Header"
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Online-Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
       <Layout>
       <Header />
        {children}
        <Footer/>
       </Layout>
      </body>
    </html>
  );
}
